apiVersion: v1
kind: Service
metadata:
  name: news-app-service
  namespace: new
spec:
  type: NodePort
  selector:
    app: news-app
  ports:
    - name: http    # Add a name here
      protocol: TCP
      port: 8000      # Service port
      targetPort: 8000  # Container port
      nodePort: 30001

