name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker for Kubernetes
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t sherinmonbiju/news-app:latest .
        docker push sherinmonbiju/news-app:latest

    # Set up kubectl
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Deploy to Kubernetes
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s/Deployment.yaml
        kubectl apply -f k8s/Service.yaml
